spring.application.name=Test06

spring.datasource.hikari.maximum-pool-size=5
# 【重要】デフォルトで動かす環境を指定（ローカル時は「local」、本番時はここを「prod」に書き換えるか環境変数で上書きする）
spring.profiles.active=prod
#spring.profiles.active=local

# 共通のJPA設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
