spring.application.name=Test06
# 接続URLを「C:/data/taskdb」のように絶対パスで分かりやすい場所に指定します
spring.datasource.url=jdbc:h2:file:C:/data/taskdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# アプリ起動時に、テーブルがない場合だけ自動作成・更新する設定
spring.jpa.hibernate.ddl-auto=update

# H2データベースの管理画面（コンソール）を使えるようにする設定
spring.h2.console.enabled=true